import type { BrainsConfig } from "./manifest.js";

// GHCR mirror of berriai/litellm-database, pushed in Task 3.
export const IMAGE_REF =
  "ghcr.io/brainmuxhq/brainmux-litellm@sha256:e53c8f4f012fe1286fcfd78b6a108cdf0865af21f735dd10cff47df93bf9f23f";

export function dbName(brain: string): string {
  return `litellm_${brain}`;
}

export function masterKeyVar(brain: string): string {
  return `${brain.toUpperCase()}_MASTER_KEY`;
}

function brainConfig(model: string): string {
  return [
    "litellm_settings:",
    "  drop_params: true",
    "",
    "model_list:",
    '  - model_name: "*"',
    "    litellm_params:",
    `      model: ${model}`,
    "",
  ].join("\n");
}

function serviceBlock(name: string, port: number, providerKey: string): string {
  return [
    `  ${name}:`,
    "    <<: *litellm-base",
    `    container_name: brainmux-${name}`,
    "    ports:",
    `      - "127.0.0.1:${port}:4000"`,
    "    environment:",
    "      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}",
    '      STORE_MODEL_IN_DB: "True"',
    `      DATABASE_URL: postgresql://litellm:\${POSTGRES_PASSWORD}@postgres:5432/${dbName(name)}`,
    `      LITELLM_MASTER_KEY: \${${masterKeyVar(name)}}`,
    `      ${providerKey}: \${${providerKey}}`,
    "    volumes:",
    `      - ./${name}.yaml:/app/config.yaml:ro`,
    "",
  ].join("\n");
}

export interface Generated {
  compose: string;
  configs: Record<string, string>;
  initSql: string;
}

export function generate(cfg: BrainsConfig): Generated {
  const names = Object.keys(cfg.brains); // insertion order preserved by YAML.parse

  const header = [
    "# GENERATED by bmux from brains.yaml — do not hand-edit.",
    "# Edit brains.yaml then run `bmux up` (regenerates) or `bmux config ...`.",
    "",
    "x-litellm-base: &litellm-base",
    `  image: ${IMAGE_REF}`,
    "  restart: unless-stopped",
    "  depends_on:",
    "    postgres:",
    "      condition: service_healthy",
    "  networks: [brainmux]",
    '  command: ["--config", "/app/config.yaml"]',
    "  logging:",
    "    driver: json-file",
    '    options: { max-size: "10m", max-file: "3" }',
    "  healthcheck:",
    `    test: ["CMD-SHELL", "python3 -c \\"import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')\\""]`,
    "    interval: 15s",
    "    timeout: 5s",
    "    retries: 5",
    "    start_period: 30s",
    "",
    "services:",
    "  postgres:",
    "    image: postgres:16-alpine",
    "    container_name: brainmux-postgres",
    "    restart: unless-stopped",
    "    networks: [brainmux]",
    "    logging:",
    "      driver: json-file",
    '      options: { max-size: "10m", max-file: "3" }',
    "    environment:",
    "      POSTGRES_USER: litellm",
    "      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}",
    "      POSTGRES_DB: litellm",
    "    volumes:",
    "      - ../data/postgres:/var/lib/postgresql/data",
    "      - ./init:/docker-entrypoint-initdb.d:ro",
    "    healthcheck:",
    '      test: ["CMD-SHELL", "pg_isready -U litellm"]',
    "      interval: 5s",
    "      timeout: 5s",
    "      retries: 10",
    "",
  ].join("\n");

  const services = names.map((n) => serviceBlock(n, cfg.brains[n].port, cfg.brains[n].providerKey)).join("");

  const footer = ["networks:", "  brainmux:", "    name: brainmux", ""].join("\n");

  const compose = header + services + footer;

  const configs: Record<string, string> = {};
  for (const n of names) configs[n] = brainConfig(cfg.brains[n].model);

  const initSql =
    "-- GENERATED by bmux — one database per brain.\n" +
    names.map((n) => `CREATE DATABASE ${dbName(n)};`).join("\n") +
    "\n";

  return { compose, configs, initSql };
}
